### ISSUE TITLE
BR evaluation doesn't work with Flop5Holdem

### ISSUE THREAD

**Issue by SavvaI** [TinkeringCode/Deep-CFR#1]
I tried to evaluate sdcfr_vs_deepcfr_h2h.py agent's exploitability with Flop5Holdem, so i changed eval_methods to br, but when I tried to launch it, program freezed on Creating BR Evaluator.

**Comment by EricSteinberger** [comment]
Hi!

This is on purpose; it is not meant to work.

Why? Because BR of Flop5Holdem is very expensive. It is even more so without any domain-specific invariance optimizations. Including code for these optimizations would increase the potential / lower the barrier for non-scientific and non-educational use, which I don't want. I recommend using LBR and RL-BR in 5FHP and bigger games.

Best Eric
